name: Specifications Annotation Workflow

on:
  pull_request:
    paths:
      - 'tests/**'

jobs:
  run_tests:
    name: logging annotations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: python bin/annotation_workflow.py
